### ISSUE TITLE
Resurrect package on CRAN

### ISSUE THREAD

**Issue by zeileis** [gamlss-dev/gamlss.ggplots#1]
Mikis @mstasinopoulos and Fernanda @fdebastiani, the package is currently archived on CRAN because the last version 2.1-2 had issues with examples in `\donttest{...}` that failed and were not corrected in time, see:

<https://www.stats.ox.ac.uk/pub/bdr/donttest/gamlss.ggplots.out>

I'm not sure if these problems were fixed already but it looks to me that loading/importing all packages needed for the examples should hopefully be straightforward. Let me know if I can help with this.

Additionally, I have updated the `Authors@R` in the `DESCRIPTION` and the `README.md` and added a `NEWS.md`.

**Comment by zeileis** [comment]
The package is still archived on CRAN but I think it would be good to have it back in order to use it for examples, etc. as Mikis did in his [Function.qmd](https://github.com/gamlss-dev/admin/blob/main/Function.qmd).

**Comment by fdebastiani** [comment]
Thanks Achim,

Do you have any suggestion to make the example properly written for CRAN?

**Comment by zeileis** [comment]
As a general strategy:

- The code you put into `\donttest{...}` needs to run successfully when tested. The CRAN does not run these checks daily but occasionally.
- To check whether the `\donttest{...}` or `\dontrun{...}` examples actually run, you can use: `R CMD check --run-donttest` and/or `--run-dontrun`, respectively.

In this specific case:

- The error message in the [output file](https://www.stats.ox.ac.uk/pub/bdr/donttest/gamlss.ggplots.out) says:

      > pp+ geom_vline(xintercept = MM$pc, colour = "gray") 
      Error in geom_vline(xintercept = MM$pc, colour = "gray") : 
        could not find function "geom_vline"
      Execution halted

  This indicates that your example assumes that the `ggplot2` package (where `geom_vline` resides) was attached to the user's search path but it actually isn't. So maybe just adding ``library("ggplot2")`` in the example is already sufficient.
- Finally, there is a message saying: `executing %dopar% sequentially: no parallel backend registered`. So maybe `gamlss.foreach` is not needed for this example?

**Comment by mstasinopoulos** [comment]
Dear Achim 

I just pass the gamlss.data to CRAN 

Next the gamlss.ggplots with correction as suggested 

Thanks
Mikis

**Comment by zeileis** [comment]
Thanks, Mikis.

When you have updated `gamlss.ggplots` here on GitHub, let me know and I'm happy to test it as well before submitting it to CRAN.

Re: gamlss.data. We need the other direction, I think. The CRAN version was much more recent and needs to be imported into the GitHub repository (see https://github.com/gamlss-dev/gamlss.data/issues/1).

**Comment by zeileis** [comment]
Just for the record: Closing this issue because `gamlss.ggplots` is back on CRAN.
